// Everything the site says lives here. Edit this file to change the text,
// add a project, or fill in your links; the pages are built from it.

const SITE = {
  name: "Storm Wassel",
  initials: "SW",
  greeting: "Hi, I'm",
  // [before, gold highlight, after]
  headline: ["I build things that ", "actually get used", " — by my friends, by me, and hopefully by your team."],
  heroSub: "Mathematics graduate · analytics · software",
  subline: "B.S. Mathematics · M.S. Applied Business Analytics candidate · Jacksonville, FL",
  openTo: "Open to data, analytics, and software roles.",

  links: {
    email: "stormwassel@gmail.com", // set to "" to hide it on the Contact page
    github: "https://github.com/M1QuickGun",
    linkedin: "https://www.linkedin.com/in/storm-wassel-7b2b3a361",
    resume: "resume.pdf",
  },

  about: [
    "I graduated from Jacksonville University in 2026 with a B.S. in Mathematics and University Honors, and I'm now working toward an M.S. in Applied Business Analytics. I like problems where math, code, and business data overlap.",
    "My academic work includes research on prime parking functions in combinatorics and machine learning projects in Python. Outside class, most of what I build starts as something I or my friends actually need: a way to keep playing our house-ruled board game online, or an assistant that handles the busywork of a job search.",
  ],

  skills: ["Python", "Java", "C++", "JavaScript", "MySQL", "Machine learning", "Statistics",
           "Data visualization", "Excel", "Node.js", "Git / GitHub", "Google Colab"],

  // Resume timeline, newest first.
  timeline: [
    { title: "M.S. Applied Business Analytics", org: "Jacksonville University · expected 2027", when: "Now" },
    { title: "B.S. Mathematics", org: "Jacksonville University · University Honors, 3.73 GPA · Pi Mu Epsilon", when: "2023–2026" },
    { title: "Research: prime parking functions", org: "Combinatorics research on mathematical patterns and statistical relationships", when: "" },
  ],
};

// resume.pdf is rendered from this plus SITE and PROJECTS (see resume.html).
// Technical Projects on the resume = every project with a `resume` line, in PROJECTS order.
const RESUME = {
  tagline: "Python, Machine Learning, Statistics",
  location: "Jacksonville, Florida",
  website: "https://storm-wassel.onrender.com",
  summary: "Mathematics graduate with strong analytical foundation and hands-on experience in Python, machine learning, and data visualization. I help teams understand complex datasets through statistical analysis and dashboard creation, with proven ability to identify patterns in academic research and collaborative projects.",

  education: [
    {
      school: "Jacksonville University", place: "Jacksonville, FL",
      degrees: [
        { degree: "Bachelor of Science in Mathematics", detail: "Graduated May 2nd, 2026 with University Honors",
          bullets: ["Honors & Scholars Program", "University GPA: Cumulative 3.73 – Magna Cum Laude"] },
        { degree: "Master of Science in Applied Business Analytics", detail: "Anticipated Graduation 2027", bullets: [] },
      ],
    },
  ],

  academicProjects: [
    "Conducted academic research on prime parking functions in combinatorics, analyzing mathematical patterns and statistical relationships",
    "Developed multiple machine learning projects analyzing datasets in Python, creating data visualizations and dashboards to present findings",
    "Executed data manipulation projects to analyze complex datasets",
    "Developed three small-scale games utilizing Java for interactive applications",
  ],

  skills: [
    ["Programming Languages", "Python, Java, C++, JavaScript"],
    ["Data Analysis & Statistics", "Descriptive statistics, Data manipulation, Machine learning"],
    ["Tools & Platforms", "Excel, MySQL, Git, Google Colab, Data Studio"],
    ["Technical Skills", "Academic research, Data visualization"],
  ],

  work: [
    { org: "Wilkinson Landscaping Contracting LLC", place: "Hunt Valley, Maryland",
      role: "Stone Worker and Lawn Maintainer", when: "May 2024 – Present (Seasonal)",
      bullets: ["Constructed paths and structures to enhance outdoor spaces",
                "Executed ad hoc landscaping projects to meet client needs"] },
    { org: "Barrett’s Grill", place: "Hunt Valley, Maryland",
      role: "Host, Food Runner, Server", when: "July 2022 – December 2022",
      bullets: ["Welcomed customers and coordinated reservations for service efficiency",
                "Facilitated communication between kitchen and staff for smooth operations"] },
    { org: "GREENIX Sales, LLC and Dish One Satellite LLC", place: "Michigan, Iowa, and Kansas",
      role: "Sales Representative", when: "Summers 2021 and 2022",
      bullets: ["Achieved record sales introducing Dish services to new customers and promoted pest control services through direct customer engagement"] },
  ],

  involvement: [
    ["Jacksonville University", "Pi Mu Epsilon math honor society and Order of Omega (2025–present); Sigma Chi Fraternity (2023–present); Math Society, Physics Society, and Chess Club (2023–present)"],
  ],
};

// category: used by the filter chips on the Projects page.
// status: short badge text. image: optional screenshot path (e.g. "img/settlers.png").
const PROJECTS = [
  {
    id: "settlers",
    title: "Settlers of the Sky",
    category: "Games",
    status: "Live",
    year: "2026",
    image: "img/settlers-closeup.webp",
    gallery: [
      { src: "img/settlers.webp", caption: "Mid-game: player panels, the 3D board and dice, resource bar, and action drawers" },
      { src: "img/settlers-board.webp", caption: "The whole board in 3D: sky-whale ports, the invasion track beside the board, and dice on the table" },
      { src: "img/settlers-town.webp", caption: "Walled towns, pastures and wheat fields, all modeled in code" },
      { src: "img/settlers-metropolis.webp", caption: "A domed metropolis inside its city walls" },
      { src: "img/settlers-robber.webp", caption: "The sky pirate balloon (the robber) and a lit beacon-tower knight" },
      { src: "img/settlers-knights.webp", caption: "Knights as beacon towers: lit when active, grey stone and smoke when not" },
      { src: "img/settlers-barbarians.webp", caption: "The armored war whale on the invasion track, with attack vs. defense strength" },
      { src: "img/settlers-dice.webp", caption: "3D dice tossed onto the table on every roll, including the event die" },
      { src: "img/settlers-p2.webp", caption: "Five-player game: a paired \"Player 2\" turn in progress" },
      { src: "img/settlers-build.webp", caption: "Build drawer with costs and remaining pieces" },
      { src: "img/settlers-lobby.webp", caption: "House rules the host picks in the lobby" },
      { src: "img/settlers-mobile.webp", caption: "Phone layout", tall: true },
    ],
    summary: "A real-time multiplayer strategy and trading game for 2–6 players on a 3D hex-tile board, with an expansion ruleset and house rules picked per game.",
    stack: ["Node.js", "Express", "Socket.IO", "three.js", "WebGL", "JavaScript"],
    links: [{ label: "Play it", url: "https://settlers-of-the-sky.onrender.com" }],
    highlights: [
      "Real-time multiplayer over Socket.IO: create a game, share an invite link, play from any browser.",
      "The server enforces every rule and only sends each player what they're allowed to see, so hands stay private.",
      "A full expansion ruleset layered on the base game: defensive units, recurring invasion events, city upgrades, and an action-card deck.",
      "A 3D board built with three.js: a framed game board on a wooden table, thick hex tiles with modeled scenery, and every piece, port and die modeled in code, with orbit, pan and zoom. Textures are painted on canvases at runtime, so there are no image or model files.",
      "Dice are tossed onto the table and tumble to the rolled faces; placed pieces drop in, rolled tiles light up, and resources fly to the players who earned them.",
      "The table sits in a 3D room the host picks in the lobby (a tavern, a sky island, an airship cabin, a campfire at night, or a plain dark room), and you can look around it.",
      "Players appear as avatars seated around the table with name tags. They watch the active player, toss the dice, act out emotes and pokes, and doze off when offline; each player can customize their own look (outfit, hat, hair, skin tone, wooden piece style).",
      "The invasion track has a brass balance scale comparing the attackers' strength to the players' defense, and a balanced-dice house rule draws rolls from a shuffled 36-card deck.",
      "5–6 player games use paired turns: after each player's turn, the player three seats over gets a build-and-bank-trade turn, so nobody waits long between turns.",
      "House rules are configurable from the lobby, because my friends and I never play by the book.",
      "Automated tests include bots playing complete 2–6 player games. Deployed on Render from GitHub.",
    ],
    resume: { stack: "JavaScript, Node.js, Socket.IO, three.js",
              line: "Built and deployed a real-time multiplayer strategy game for 2–6 players with a 3D three.js board, a server-authoritative rules engine, a full expansion ruleset, configurable house rules, 3D room scenes with seated player avatars, and automated tests that simulate complete games" },
  },
  {
    id: "atlas",
    title: "ATLAS",
    category: "AI",
    status: "Private",
    year: "2026",
    image: "img/atlas-architecture.svg",
    imageFit: "contain",
    summary: "A personal AI operating system: specialised agents, persistent memory, and a task engine that automates real work with a human approval step before anything consequential.",
    stack: ["Python", "OpenAI API", "SQLite", "FastAPI", "React", "Playwright", "pytest"],
    links: [],
    highlights: [
      "Multi-agent design: an orchestrator delegates to research, personal, and developer agents, each with a whitelisted set of tools.",
      "Tool registry with per-agent permissions, audit logging, and cost tracking on every model call.",
      "Persistent memory, a task engine and scheduler, and an objective planner that breaks goals into steps.",
      "Read-only Gmail and Calendar integration using the narrowest OAuth scopes.",
      "An end-to-end job search pipeline: candidate profile, job fit scoring, and tailored application packages, with a hard human approval step before anything is submitted.",
      "A live Control Center dashboard (React + FastAPI) shows what ATLAS is doing, what it's waiting on, and why anything failed.",
      "Built in reviewed, test-first phases: over 2,400 automated tests.",
    ],
    resume: { stack: "Python, OpenAI API, SQLite",
              line: "Designed a multi-agent AI assistant with tool permissions, persistent memory, audit logging, and a task scheduler; automates job-search workflows with human approval before any submission, backed by 2,400+ automated tests" },
  },
  {
    id: "broken-blade",
    title: "Broken Blade",
    category: "Games",
    status: "In progress",
    year: "2026",
    image: "img/broken-blade.webp",
    gallery: [
      { src: "img/broken-blade-intro.webp", caption: "The four-panel story intro: the blade shatters and the King casts his son from the summit", wide: true },
      { src: "img/broken-blade-foothills.webp", caption: "The Foothills, where Storm wakes with only the hilt" },
      { src: "img/broken-blade-glade.webp", caption: "The Sunken glade, deeper in the foothills" },
      { src: "img/broken-blade-centipede.webp", caption: "Boss of the Foothills: the Guardian Centipede, risen" },
      { src: "img/broken-blade-village.webp", caption: "The Frozen village, its people caught where they stood" },
      { src: "img/broken-blade-icefall.webp", caption: "The Icefall hall, with a frozen thrall" },
      { src: "img/broken-blade-colossus.webp", caption: "Boss of the Frozen village: the Frost Colossus, frozen into the arena wall" },
      { src: "img/broken-blade-colossus-unbound.webp", caption: "The Frost Colossus, unbound" },
      { src: "img/broken-blade-refuge.webp", caption: "The Refuge, the survivors' camp under the Crossroads" },
      { src: "img/broken-blade-fire-slopes.webp", caption: "The Fire slopes and the burned village" },
      { src: "img/broken-blade-drake.webp", caption: "Boss of the Fire slopes: the Ashen Drake, asleep in the great forge" },
      { src: "img/broken-blade-drake-unbound.webp", caption: "The Ashen Drake, unbound" },
      { src: "img/broken-blade-peaks.webp", caption: "The Lightning peaks: rain, wind and lightning" },
      { src: "img/broken-blade-stormcaller-bound.webp", caption: "Boss of the Lightning peaks: the Stormcaller, chained in the spire" },
      { src: "img/broken-blade-stormcaller.webp", caption: "The Stormcaller, freed" },
      { src: "img/broken-blade-last-stand.webp", caption: "The Last Stand, the summit battlefield under the castle gate" },
      { src: "img/broken-blade-map.webp", caption: "World map: foothills, frozen village, fire slopes and lightning peaks, with rest shrines and bosses", wide: true },
      { src: "img/broken-blade-enemies.webp", caption: "Enemies: mossy beetle, frozen thrall and hatchling", wide: true },
      { src: "img/broken-blade-run.webp", caption: "Run cycle with the full blade" },
      { src: "img/broken-blade-attack.webp", caption: "Full-blade slash with the lightning trail" },
      { src: "img/broken-blade-attack2.webp", caption: "Overhead swing that ends in a ring of fire and lightning" },
      { src: "img/broken-blade-stages.webp", caption: "Storm's sword grows with each recovered piece: hilt, ice, fire, lightning, full blade", wide: true },
      { src: "img/broken-blade-animations.webp", caption: "Idle, run and two attack animations, drawn for every blade stage", wide: true },
    ],
    summary: "A dark fantasy metroidvania I'm building for an eventual Steam release. The sword that sealed an ancient evil has shattered, and each piece grants a new ability. The game is now playable start to finish: six regions, 72 rooms, ten boss fights and an ending, in playtesting ahead of release.",
    stack: ["Godot 4", "GDScript", "Python"],
    links: [{ label: "View code", url: "https://github.com/M1QuickGun/broken-blade" }],
    highlights: [
      "Story and world design are my own: the last surviving prince returns after twenty years to a kingdom split between fragments of the evil, each bound to a piece of the blade.",
      "Ability-gated map design: an ice dash first, then the player chooses the order of a fire double jump and a lightning shockline, so both routes have to work. A wall jump is now the first pickup, in the opening room.",
      "Tight platforming: variable jump height, a grace window for late jumps, input buffering, and safe-ground respawns after hazards. Wall cling and wall jump let Storm slide down a wall and kick off it, and grabbing a wall restores the double jump.",
      "Four-way melee combat with pogo bounces off enemies and spikes, hit-stop, knockback, and attack reach that grows with each blade piece.",
      "Pixel-art hero with idle, run, attack and wall-cling animations for each blade stage, so the sword visibly grows as pieces are recovered. The lightning shockline fires the blade's tip on a barbed-wire line and drags Storm to where it lands, and the ice dash is a ground slide that leaves a frost streak.",
      "Music crossfades between tracks set per room: an exploration theme and a frozen-land theme.",
      "Ten boss fights: a guardian centipede in the foothills that digs and bursts out of the floor in a fixed, learnable order, plus bosses fought twice in two different arenas: a frost colossus, first frozen into the arena wall and then broken free in its throne; an ashen drake, grounded in the forge and then airborne; and a stormcaller, chained in a spire and then freed. A two-phase final fight in the castle ends the game, and an optional side boss hides off the lift shaft. Bosses ring a warning before their biggest blows.",
      "The fire slopes and lightning peaks now have their own tilesets, painted backdrops, weather and sound, plus new enemies (ash bats and spark wisps that charge an aim line before firing).",
      "The world and its systems: an elite foe in every region, a crown economy with shops in a survivors' refuge, hidden survivors to find, a trial room per region, fast travel between shrines, a map with boss and shop markers, and a journal that records every foe and sign.",
      "Release polish: three save slots with safe, backed-up writes, rebindable keys and controller support, accessibility and video options, a hard mode and boss rush after the ending, achievements, a demo build, and all on-screen text routed through a translation table.",
      "Music and ambient sound for every region, with footsteps that change with the ground, all synthesized by Python scripts; Steam store art is generated from the game's own paintings and font.",
      "New enemies (a charging beetle, a shambling frozen thrall, a burrowing grub), painted village and cavern backdrops with falling snow, and grapple rings Storm can hang from by his sword.",
      "A full game loop: title screen, autosaving at shrines, pickups, bosses and new rooms, a pause menu with volume and fullscreen, a map of visited rooms, a four-panel story intro, and synthesized sound effects generated by a Python script.",
      "The regions are laid out with a reachability checker that verifies each room can be completed with the abilities the player will have.",
      "Rooms are written as text maps and turned into collision, hazards, doors and enemies in code, so new areas are quick to sketch and test.",
      "An automated playtest drives the character through a full route and saves screenshots, which caught a level-layout bug before any manual play.",
    ],
    resume: { stack: "Godot 4, GDScript, Python",
              line: "Building a complete metroidvania (72 rooms, ten boss fights, an ending) for an eventual Steam release, with ability-gated level design, responsive platforming and melee combat, a reachability checker, and an automated smoke test that builds every room and boss" },
  },
  {
    id: "desk-car",
    title: "Desk Car Organizer",
    category: "3D Design",
    status: "Prototype",
    year: "2026",
    image: "img/desk-car-hero.webp",
    gallery: [
      { src: "img/desk-car-front.webp", caption: "Front: framed grille with badge, swept headlights with lens blocks, and a barred lower intake" },
      { src: "img/desk-car-top.webp", caption: "Top down: the card slot and pen holes sit between the hood creases and fender crests" },
      { src: "img/desk-car-side.webp", caption: "Side: flared wheel arch and a 10-spoke wheel" },
      { src: "img/desk-car-back.webp", caption: "The flat back and base, so it prints without supports" },
    ],
    summary: "A 3D-printable desk organizer shaped like the front end of an electric crossover, with a business-card slot and two pen holes. The whole model is generated by a Python script.",
    stack: ["Python", "NumPy", "SciPy", "scikit-image", "trimesh", "3D printing"],
    links: [],
    highlights: [
      "Started from a friend's design that didn't look like the car, so I rebuilt it from scratch in code from the real car's approximate dimensions and a reference photo.",
      "The body is modeled as a voxel solid: hood, creases, fender crests, flares and nose are shaped with math, then rounded with signed-distance-field operations.",
      "Surface details (grille frame, badge, headlight lens blocks, intake bars, shut lines, 10-spoke wheels) are carved or raised relative to the surface, deliberately exaggerated so they read at desk-toy size.",
      "Marching cubes turns the voxels into a mesh, and Taubin smoothing removes the stair-stepping without shrinking the model. The output is watertight and prints with no supports.",
      "Pockets are sized for real objects: a 94 × 8 mm card slot that fits business and credit cards, and two 20 mm pen holes, checked by slicing the finished mesh.",
      "Every dimension is a parameter, so scale, hole sizes and positions change by editing a number and rerunning the script.",
    ],
  },
  {
    id: "settlers-analytics",
    title: "Game analytics",
    category: "Data",
    status: "Coming soon",
    summary: "Logging every roll, trade, and build from Settlers games to produce post-game reports and train a smarter AI opponent.",
    stack: ["SQL", "Python", "Simulation"],
    links: [],
    highlights: [],
  },
];
